backend:
  name: git-gateway
media_folder: src/images
public_folder: ""
publish_mode: editorial_workflow

collections:
  - label: Home
    name: home
    files:
      - label: Content
        name: content
        file: src/content/files/home.json
        fields:
          - label: Text sections
            label_singular: Section
            name: text_sections
            widget: list
            fields:
              - { label: Highlight text, name: highlight, widget: string }
              - { label: Paragraph, name: paragraph, widget: markdown }

  - label: About
    name: about
    files:
      - label: Content
        name: content
        file: src/content/files/about.json
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - label: Position
                name: position
                widget: string
                required: false
              - label: Bio
                name: bio
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: string
                    required: false
                  - label: Paragraphs
                    name: paragraphs
                    widget: list
                    field:
                      { label: Paragraph, name: paragraph, widget: markdown }
              - label: Photos
                name: photos
                widget: list
                field: { label: Image, name: image, widget: image }
              - label: Timeline
                name: timeline
                widget: list
                fields:
                  - { label: Date, name: date, widget: string }
                  - { label: Description, name: description, widget: markdown }

  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: src/content/files/home.json
        fields:
          - label: Text sections
            name: text_sections
            widget: list
            fields:
              - { label: Highlight text, name: highlight, widget: string }
              - { label: Paragraph, name: paragraph, widget: markdown }

      - label: About
        name: about
        file: src/content/files/about.json
        # media_folder: "/about"
        # public_folder: ""
        fields:
          - { label: Title, name: title, widget: string, required: false }
          - { label: Body, name: body, widget: markdown, required: false }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - label: Position
                name: position
                widget: string
                required: false
              - label: Bio
                name: bio
                widget: object
                fields:
                  - label: Title
                    name: title
                    widget: string
                    required: false
                  - label: Paragraphs
                    name: paragraphs
                    widget: list
                    field:
                      { label: Paragraph, name: paragraph, widget: markdown }
              - label: Photos
                name: photos
                widget: list
                field: { label: Image, name: image, widget: image }
              - label: Timeline
                name: timeline
                widget: list
                fields:
                  - { label: Date, name: date, widget: string }
                  - { label: Description, name: description, widget: markdown }
